cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g gulp-cli
  - npm install
script:
  - gulp
addons:
  browserstack:
    username: "SkyzohKey"
    acess_key:
      secure: "W1GV0cyuMthv6o9YUBQ8rbUaIa/q7PTVSsFmNYllnrnYm09fhXp3xPuzXhcuhjsLpBk07rFawyy5ezgAuHMVXVx5QjLIz2B0JNV6xGphW5y8kfdIhSl0fK07rLiGNnvhF/2XCaOxyWVklcHkb7oILwrmSZwRnhriozxI53qFLvDv3iHbt7oL374EBZmR2cTBxI7DTybPqRiTNw7005HTXwYP0Z/VHj8qoYEdjwYHPu7hKprzlWOQucwFNNQDCZpH6uh6WHWS4wfdukQKROUDmYj1DEVt3Smvd2b5sV26tFhOz9S5OTnCo3YS2gqR3ucA341NdICVfI4t+WmB7lSbW0rySNSfdyn6UupcI/QLMBDZ+Rm2mTJj1MZpsz6wpyx0KzjkfKUbDs3S9xrWeIRtsECLAsnUJPhI0ymMeCQmHSpj4xU832IVDgIRvzSw+P/JwTUPhaFfIqr9OP7uPlWA/BeaCu03YGxXwuNii9zvb//yUdCzQhkW3vJfrtqbL3kUZ+sQuXAzBDzV28G7Z12+M0EFmN3BJ486HIyztly4e6lTKwU8y2C6wkhJjWG9jpTqCv9I/ufTcyF5AXXKX83S4RJkA5H89mSMqxCKDynANA5RTpL8EhhxS7yhH9hqeoJxV7A6LcYQayQoKrlltoBPg5hYaS2QCnVkDBqHjeuMrG0="