cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp-cli
- npm install
script:
- gulp
addons:
  browserstack:
    username: SkyzohKey
    access_key:
      secure: $BROWSERSTACK_ACCESS_KEY

