cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp-cli
- npm install
script:
- gulp
addons:
  browserstack:
    username: SkyzohKey
    access_key:
      secure: $BROWSERSTACK_ACCESS_KEY # Set in travis-ci.org dashboard
deploy:
  provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master