language: node_js
node_js:
- '5'

cache:
  directories:
  - node_modules

before_script:
- npm install -g gulp-cli
- npm install

script:
- gulp --env production

addons:
  browserstack:
    username: skyzohkey3
    access_key:
      secure: "$BROWSERSTACK_ACCESS_KEY"

deploy:
  provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
